//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace citPOINT.PrefApp.Data.Web.eNegMailService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="eNegMailService.MailServiceSoap")]
    public interface MailServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MailServiceSoap/SendMailMessage", ReplyAction="http://tempuri.org/MailServiceSoap/SendMailMessageResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.DomainServices.Hosting.DomainServiceFault), Action="http://tempuri.org/MailServiceSoap/SendMailMessageDomainServiceFault", Name="DomainServiceFault", Namespace="DomainServices")]
        void SendMailMessage(string from, string to, string bcc, string cc, string subject, string body);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MailServiceSoapChannel : citPOINT.PrefApp.Data.Web.eNegMailService.MailServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MailServiceSoapClient : System.ServiceModel.ClientBase<citPOINT.PrefApp.Data.Web.eNegMailService.MailServiceSoap>, citPOINT.PrefApp.Data.Web.eNegMailService.MailServiceSoap {
        
        public MailServiceSoapClient() {
        }
        
        public MailServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MailServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MailServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MailServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void SendMailMessage(string from, string to, string bcc, string cc, string subject, string body) {
            base.Channel.SendMailMessage(from, to, bcc, cc, subject, body);
        }
    }
}
